### ISSUE TITLE
Feature Request: Add a "Duplicate Record" Button to ItemList Component

### ISSUE THREAD

**Issue by lucasferreiralimax** [criar-art/wallet.digitalz.app#11]
We would like to enhance the `ItemList` component by adding a new button that enables users to duplicate existing records. This feature will streamline the process of creating new records by reusing existing data, thereby reducing repetitive input.

#### Expected Behavior
- A new button should appear alongside the existing edit and delete buttons within the `ItemList` options.
- When the button is pressed, a new record should be created with the same details as the original, but with a new ID and potentially other relevant changes (e.g., timestamp, unique fields).
- The button should be available regardless of the record type (e.g., "expense").

#### Proposed Button Details
- **Icon**: Use a `MaterialIcons` duplicate icon or a `FontAwesome` copy icon (we're open to suggestions).
- **Label**: `"Duplicate Register"`.
- **Button Style**: Similar to the existing edit and delete buttons (i.e., a round button with a border and icon).
- **Action**: Trigger a function that handles the duplication logic.

#### Implementation Example
Below the existing edit and delete buttons, add the following code for the duplicate button:

```jsx
<Button
  twClass="z-20 w-14 h-14 m-2 rounded-full border-2 border-gray-300 dark:border-zinc-500 bg-white dark:bg-zinc-800"
  onPress={props.duplicate}
  label={`${t("common.duplicate_register")} ${props.item.name}`}
  icon={
    <MaterialIcons
      name="content-copy"
      size={22}
      color={colorScheme === "dark" ? "white" : "black"}
    />
  }
/>
```

#### Duplication Logic
Implement the duplication logic in the `props.duplicate` method as follows:

```ts
import { v4 as uuidv4 } from 'uuid';

setDuplicateRegisterExpense(state: CommonState, action: any) {
  console.log('action.payload', action.payload);

  const duplicatedRegister = {
    ...action.payload,
    id: uuidv4(),  // Generate a new unique ID
    date: new Date().toISOString(),  // Optionally update timestamp
  };

  console.log('duplicatedRegister', duplicatedRegister);

  state.registers = sortDataByDateDesc([...state.registers, duplicatedRegister]);
},
```

### Tasks
- [x] Create a new button for duplicating records in the `ItemList` component.
- [x] Implement duplication logic in the `props.duplicate` method to handle creating a new record with a unique ID and updated timestamp.
- [x] Ensure the new record is correctly rendered in the list after duplication.
